/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pooitec1.alibaba2.view;

import com.pooitec1.alibaba2.controller.SaleController;
import com.pooitec1.alibaba2.entity.LoteProduct;
import com.pooitec1.alibaba2.entity.Product;
import com.pooitec1.alibaba2.view.resources.TableModelListenerProduct;
import com.pooitec1.alibaba2.view.resources.TableModelProduct;
import com.pooitec1.alibaba2.view.resources.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author nadia
 */
public class JPanel_VentaPaso3 extends javax.swing.JPanel {

    //Validado de campos
    ValidadorDeCampos validadorDeCampos;

    //variables de tabla
    private final TableModelProduct tableModelProduct;

    private LoteProduct loteProductSelected;

    SaleController controlador;
    private JPanelAplication panelMenu;

    /**
     * Creates new form JPanel_VentaPaso3
     */
    public JPanel_VentaPaso3(JPanelAplication panelMenu, SaleController controladorP) {
        this.validadorDeCampos = new ValidadorDeCampos();

        this.tableModelProduct = new TableModelProduct();

        this.controlador = controladorP;
        this.panelMenu = panelMenu;
        
        
        initComponents();
        
        this.jtbl_products.getSelectionModel().addListSelectionListener(new TableModelListenerProduct(this));
       
        validadarCampos();
        
        setupBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_prodcutname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_products = new javax.swing.JTable();
        jbtn_cancelarventapaso3 = new javax.swing.JButton();
        jbtn_atrasventapaso3 = new javax.swing.JButton();
        jbtn_agregarproduct = new javax.swing.JButton();
        jlbl_descripcion = new javax.swing.JLabel();
        jlbl_tipoproducto = new javax.swing.JLabel();
        jlbl_precio = new javax.swing.JLabel();
        jtxf_productname = new javax.swing.JTextField();
        JLbl_descripcion = new javax.swing.JLabel();
        JLbl_productType = new javax.swing.JLabel();
        JLbl_price = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jlbl_prodcutname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbl_prodcutname.setText("Product Description");

        jtbl_products.setModel(tableModelProduct);
        jScrollPane1.setViewportView(jtbl_products);

        jbtn_cancelarventapaso3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtn_cancelarventapaso3.setText("CANCEL");
        jbtn_cancelarventapaso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarventapaso3ActionPerformed(evt);
            }
        });

        jbtn_atrasventapaso3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtn_atrasventapaso3.setText("BACK");
        jbtn_atrasventapaso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atrasventapaso3ActionPerformed(evt);
            }
        });

        jbtn_agregarproduct.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtn_agregarproduct.setText("ADD");
        jbtn_agregarproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarproductActionPerformed(evt);
            }
        });

        jlbl_descripcion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbl_descripcion.setText("Description:");

        jlbl_tipoproducto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbl_tipoproducto.setText("Proyuct type:");

        jlbl_precio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbl_precio.setText("Price:");

        jtxf_productname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxf_productnameActionPerformed(evt);
            }
        });
        jtxf_productname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxf_productnameKeyReleased(evt);
            }
        });

        JLbl_descripcion.setText("jLabel1");

        JLbl_productType.setText("jLabel2");

        JLbl_price.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_descripcion)
                                .addGap(18, 18, 18)
                                .addComponent(JLbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_tipoproducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JLbl_productType, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_precio)
                                .addGap(40, 40, 40)
                                .addComponent(JLbl_price, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbtn_cancelarventapaso3)
                        .addGap(134, 134, 134)
                        .addComponent(jbtn_atrasventapaso3)
                        .addGap(131, 131, 131)
                        .addComponent(jbtn_agregarproduct))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_prodcutname)
                                .addGap(18, 18, 18)
                                .addComponent(jtxf_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_prodcutname)
                    .addComponent(jtxf_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jlbl_descripcion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLbl_descripcion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_tipoproducto)
                    .addComponent(JLbl_productType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_precio)
                    .addComponent(JLbl_price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelarventapaso3)
                    .addComponent(jbtn_atrasventapaso3)
                    .addComponent(jbtn_agregarproduct))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarventapaso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarventapaso3ActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido(); // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_cancelarventapaso3ActionPerformed

    private void jbtn_atrasventapaso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atrasventapaso3ActionPerformed
        JPanel_VentaPaso2 panelPaso2 = new JPanel_VentaPaso2(this.panelMenu, this.controlador);

        panelPaso2.setSize(814, 600);

        this.panelMenu.limpiarPanelContenido();

        this.panelMenu.getjPanel_contenido().add(panelPaso2);

        this.panelMenu.repaint();
        this.panelMenu.validate(); // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_atrasventapaso3ActionPerformed

    private void jtxf_productnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxf_productnameKeyReleased
        if (this.jtxf_productname.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
             this.tableModelProduct.setProducts(this.controlador.findProductByDescription(this.jtxf_productname.getText()));

            //Refrescar el modelo en la tabla
            this.tableModelProduct.fireTableDataChanged();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtxf_productnameKeyReleased

    private void jtxf_productnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxf_productnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxf_productnameActionPerformed

    private void jbtn_agregarproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarproductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbl_descripcion;
    private javax.swing.JLabel JLbl_price;
    private javax.swing.JLabel JLbl_productType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_agregarproduct;
    private javax.swing.JButton jbtn_atrasventapaso3;
    private javax.swing.JButton jbtn_cancelarventapaso3;
    private javax.swing.JLabel jlbl_descripcion;
    private javax.swing.JLabel jlbl_precio;
    private javax.swing.JLabel jlbl_prodcutname;
    private javax.swing.JLabel jlbl_tipoproducto;
    private javax.swing.JTable jtbl_products;
    private javax.swing.JTextField jtxf_productname;
    // End of variables declaration//GEN-END:variables

    /**
     * Selecciona una fila de la tabla, devolviendo un objeto Buyer/Cliente
     */
    public void seleccionarProducto() {
        //obtiene el indice de la fila seleccionada en la tabla de buyer
        int filaSeleccionada = this.jtbl_products.getSelectedRow();
        // si la fila esta seleccionada, seteamos  buyer auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            this.loteProductSelected = this.tableModelProduct.getProductIn(filaSeleccionada);
            this.JLbl_descripcion.setText(this.loteProductSelected.getProduct().getCodProd());
            this.JLbl_productType.setText(this.loteProductSelected.getProduct().getProductType().getDescription());
          //  this.JLbl_price.setText(this.loteProductSelected.getSalePrice());

        }
    }

    private void validadarCampos() {
        this.validadorDeCampos.validarSoloLetras(jtxf_productname);
        this.validadorDeCampos.LimitarCaracteres(jtxf_productname, 20);
    }

    private void setupBotones() {
        this.validadorDeCampos.habilitarBoton(true, jbtn_cancelarventapaso3, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }

}
