/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pooitec1.alibaba2.view;

import com.pooitec1.alibaba2.controller.SaleController;
import com.pooitec1.alibaba2.entity.Buyer;
import com.pooitec1.alibaba2.view.resources.TableModelBuyer;
import com.pooitec1.alibaba2.view.resources.TableModelListenerBuyer;
import com.pooitec1.alibaba2.view.resources.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author nadia
 */
public class JPanel_VentaPaso1 extends javax.swing.JPanel {
    //Validado de campos

    ValidadorDeCampos validadorDeCampos;

    //variables de tabla
    private final TableModelBuyer tableModelBuyer;

    private Buyer buyerSeleccionado;

    SaleController controlador;
    private JPanelAplication panelMenu;

    /**
     * Creates new form JPanel_VentaPaso1
     */
    public JPanel_VentaPaso1(JPanelAplication panelMenu, SaleController controladorP) {
        this.validadorDeCampos = new ValidadorDeCampos();
        //JTable vacio
        this.tableModelBuyer = new TableModelBuyer();

        this.controlador = controladorP;
        this.panelMenu = panelMenu;
        initComponents();

        this.jtb_buyers.getSelectionModel().addListSelectionListener(new TableModelListenerBuyer(this));

        validadarCampos();

        setupBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtx_buyerDni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_buyers = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_siguientepaso1 = new javax.swing.JButton();
        jlbl_buyerfirstname = new javax.swing.JLabel();
        jlbl_buyerlastname = new javax.swing.JLabel();
        jlbl_dnibuyer = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbl_address = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_phone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Buyer DNI:");

        jtx_buyerDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_buyerDniActionPerformed(evt);
            }
        });
        jtx_buyerDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtx_buyerDniKeyReleased(evt);
            }
        });

        jtb_buyers.setModel(tableModelBuyer);
        jScrollPane1.setViewportView(jtb_buyers);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Dni:");

        jbtn_cancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jbtn_siguientepaso1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtn_siguientepaso1.setText("SIGUIENTE");
        jbtn_siguientepaso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_siguientepaso1ActionPerformed(evt);
            }
        });

        jlbl_buyerfirstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_buyerfirstname.setText("jLabel7");

        jlbl_buyerlastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_buyerlastname.setText("jLabel8");

        jlbl_dnibuyer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_dnibuyer.setText("jLabel9");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Address");

        jlbl_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_address.setText("jLabel7");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Phone");

        jlbl_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_phone.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jbtn_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_siguientepaso1)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtx_buyerDni, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlbl_dnibuyer, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                                        .addComponent(jlbl_buyerfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jlbl_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbl_buyerlastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                                    .addComponent(jlbl_phone))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtx_buyerDni, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlbl_dnibuyer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbl_buyerfirstname))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_buyerlastname)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlbl_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlbl_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelar)
                    .addComponent(jbtn_siguientepaso1))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido(); // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jbtn_siguientepaso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_siguientepaso1ActionPerformed
        if (this.buyerSeleccionado != null) {
            this.controlador.getNewSale().setBuyer(buyerSeleccionado);
             JPanel_VentaPaso2 panelPaso2 = new JPanel_VentaPaso2(this.panelMenu, this.controlador);

            panelPaso2.setSize(814, 600);
            this.panelMenu.limpiarPanelContenido();

            this.panelMenu.getjPanel_contenido().add(panelPaso2);
            this.panelMenu.repaint();
            this.panelMenu.validate();

        } else {
            System.out.println("selecciona cliente");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_siguientepaso1ActionPerformed
   
    private void jtx_buyerDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_buyerDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_buyerDniActionPerformed

    private void jtx_buyerDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_buyerDniKeyReleased
        if (this.jtx_buyerDni.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
            this.tableModelBuyer.setBuyers(this.controlador.findBuyerByDni(this.jtx_buyerDni.getText()));

            //Refrescar el modelo en la tabla
            this.tableModelBuyer.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtx_buyerDniKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_siguientepaso1;
    private javax.swing.JLabel jlbl_address;
    private javax.swing.JLabel jlbl_buyerfirstname;
    private javax.swing.JLabel jlbl_buyerlastname;
    private javax.swing.JLabel jlbl_dnibuyer;
    private javax.swing.JLabel jlbl_phone;
    private javax.swing.JTable jtb_buyers;
    private javax.swing.JTextField jtx_buyerDni;
    // End of variables declaration//GEN-END:variables

    /**
     * Selecciona una fila de la tabla, devolviendo un objeto Buyer/Cliente
     */
    public void seleccionarSocio() {
        //obtiene el indice de la fila seleccionada en la tabla de buyer
        int filaSeleccionada = this.jtb_buyers.getSelectedRow();
        // si la fila esta seleccionada, seteamos  buyer auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            this.buyerSeleccionado = this.tableModelBuyer.getBuyerIn(filaSeleccionada);
            this.jlbl_buyerfirstname.setText(this.buyerSeleccionado.getFirstName());
            this.jlbl_buyerlastname.setText(this.buyerSeleccionado.getLastName());
            this.jlbl_dnibuyer.setText(this.buyerSeleccionado.getDni());
            this.jlbl_address.setText(this.buyerSeleccionado.getAddress());
            this.jlbl_phone.setText(this.buyerSeleccionado.getPhone());

        }
    }

    private void validadarCampos() {
        this.validadorDeCampos.validarSoloNumero(jtx_buyerDni);
        this.validadorDeCampos.LimitarCaracteres(jtx_buyerDni, 8);
    }

    private void setupBotones() {
        this.validadorDeCampos.habilitarBoton(true, jbtn_cancelar, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }

}
